name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: any
  flutter:
    sdk: flutter
  firebase_auth:
    path: ../
  google_sign_in: ^5.0.0-nullsafety
  flutter_signin_button: ^1.0.0
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_dynamic_links:
    path: ../../../firebase_dynamic_links
  uuid: ^2.0.2

dependency_overrides:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface
  firebase_dynamic_links:
    path: ../../../firebase_dynamic_links

dev_dependencies:
  pedantic: 1.10.0-nullsafety.3
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter:
  uses-material-design: true
