name: cloud_functions_web
description: The web implementation of cloud_functions
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions_web
version: 3.1.4-nullsafety.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

dependencies:
  cloud_functions_platform_interface: ^4.0.2-nullsafety.0
  firebase_core: ^0.7.0-nullsafety.0
  firebase_core_web: ^0.2.2-nullsafety.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3-nullsafety.3

dev_dependencies:
  firebase_core_platform_interface: ^3.0.2-nullsafety.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.2
  pedantic: 1.10.0-nullsafety.3

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFunctionsWeb
        fileName: cloud_functions_web.dart
