name: firebase_database_example
description: Demonstrates how to use the firebase_database plugin.

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.9.1+hotfix.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database:
    path: ../
  firebase_core:
    path: ../../firebase_core/firebase_core

dependency_overrides:
  quiver: ">=3.0.0-nullsafety.2 <4.0.0"
  firebase_core:
    path: ../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../firebase_core/firebase_core_platform_interface

dev_dependencies:
  pedantic: ^1.8.0
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.6.1

flutter:
  uses-material-design: true
